name: laf_flutter
description: Application LAF EA Metz
publish_to: 'none' # Remove this line si tu veux publier sur pub.dev

version: 1.1.7+17

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  package_info_plus: ^4.2.0
  share_plus: ^7.2.1
  pdf: ^3.10.4
  printing: ^5.12.0
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  url_launcher: ^6.2.6




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1   # <-- Corrigé : PAS dans flutter_test !

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Roboto-Regular.ttf

